// Code generated by cmd/genblocks; DO NOT EDIT.

export type BlockType =
  | "text"
  | "metrics"
  | "table"
  | "timeseries"
  | "bar"
  | "heatmap"
  | "trace_waterfall"
  | "topology"
  | "flame_graph"
  | "sankey"
  | "dep_matrix"
  | "endpoints"
  | "correlation"
  | "logs";

export interface Block {
  type: BlockType;
  data: unknown;
}

export interface TextBlockData {
  content: string;
}

export interface MetricItem {
  label: string;
  value: number;
  unit: string;
  status: string;
}

export interface MetricsBlockData {
  items: MetricItem[];
}

export interface TableColumn {
  key: string;
  label: string;
  align?: string;
}

export interface TableBlockData {
  columns: TableColumn[];
  rows: Record<string, unknown>[];
}

export interface TimeseriesSeries {
  label: string;
  color?: string;
  values: number[];
}

export interface TimeseriesBlockData {
  title: string;
  series: TimeseriesSeries[];
  labels: string[];
  yLabel?: string;
}

export interface BarItem {
  label: string;
  value: number;
  color?: string;
}

export interface BarBlockData {
  title: string;
  bars: BarItem[];
  yLabel?: string;
  horizontal?: boolean;
}

export interface HeatmapBlockData {
  title: string;
  buckets: number[];
  times: string[];
  values: number[][];
}

export interface TraceSpan {
  id: string;
  parent: string | null;
  service: string;
  operation: string;
  start: number;
  duration: number;
  status: string;
}

export interface TraceWaterfallData {
  spans: TraceSpan[];
}

export interface TopologyNode {
  id: string;
  status: string;
  rpm: number;
  p95: number;
  errors: number;
}

export interface TopologyEdge {
  source: string;
  target: string;
  rpm: number;
  errorRate: number;
}

export interface TopologyData {
  nodes: TopologyNode[];
  edges: TopologyEdge[];
}

export interface FlameFrame {
  name: string;
  depth: number;
  x: number;
  w: number;
  self: number;
  total: number;
  service: string;
}

export interface FlameGraphData {
  frames: FlameFrame[];
}

export interface SankeyNode {
  id: string;
  label: string;
  rpm: number;
  status?: string;
}

export interface SankeyLink {
  source: string;
  target: string;
  value: number;
}

export interface SankeyData {
  nodes: SankeyNode[];
  links: SankeyLink[];
}

export interface DepMatrixCell {
  from: string;
  to: string;
  errorRate: number;
  rpm: number;
  p95: number;
}

export interface DepMatrixData {
  services: string[];
  cells: DepMatrixCell[];
}

export interface EndpointInfo {
  method: string;
  path: string;
  rpm: number;
  p50: number;
  p95: number;
  p99: number;
  errorRate: number;
  status: string;
}

export interface EndpointsData {
  endpoints: EndpointInfo[];
}

export interface CorrelationMarker {
  t: string;
  label: string;
  severity: string;
}

export interface CorrelationPanel {
  label: string;
  color: string;
  values: number[];
  baseline?: number;
  markers?: CorrelationMarker[];
}

export interface CorrelationData {
  times: string[];
  panels: CorrelationPanel[];
}

export interface LogEntry {
  time: string;
  severity: string;
  service: string;
  body: string;
  traceId?: string;
}

export interface LogsBlockData {
  entries: LogEntry[];
}

// Chat event types (WebSocket protocol)
export interface ChatEvent {
  type: "token" | "tool_call" | "tool_result" | "error" | "done";
  content?: string;
  name?: string;
  input?: string;
  error?: string;
  id?: string;
  blocks?: Block[];
}

// Client message (sent to server)
export interface ClientMessage {
  type: "message" | "cancel" | "clear";
  content?: string;
  window?: number;
  namespace?: string;
}

// Bookmark
export interface Bookmark {
  id: string;
  question: string;
  answer_html: string;
  created_at: string;
}
