include:
  - path: demo/docker-compose.yaml
    env_file: demo/.env

services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-v@labstack.com}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /data/caddy:/data
      - /data/caddy-config:/config

  fanout-site:
    image: ghcr.io/labstack/fanout-site:${VERSION:-latest}
    container_name: fanout-site
    restart: unless-stopped
    expose:
      - "80"
