version: "0.5"

processes:
  server:
    command: air
    working_dir: .
    environment:
      - OTEL_SERVICE_NAME=fanout
    env_file: ./.env

  web:
    command: bun run dev
    working_dir: ./web

  site:
    command: bash -c 'if [ -f package.json ]; then bun run dev --host --port 7522; else echo "site not scaffolded yet"; sleep infinity; fi'
    working_dir: ./site
