version: "0.5"

processes:
  server:
    command: air
    working_dir: .
    environment:
      - OTEL_SERVICE_NAME=fanout
    env_file: ./.env

  web:
    command: bun run dev
    working_dir: ./web

  site:
    command: bun run dev --host --port 7522
    working_dir: ./site
