package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/labstack/fanout/internal/api"
)

// roleCount is set by renderRoles so the summary line can report it.
var roleCount []string

// capabilityNotes is the authored half: what a capability lets someone do, in a
// reader's terms. The matrix itself comes from the middleware.
//
// A capability with no note here fails the run. That is deliberate — the reason
// this page is generated at all is that its hand-written predecessor said
// `viewer` could not run the agent while roleCapabilities granted exactly that,
// which is the sort of claim an operator acts on when deciding who to admit.
var capabilityNotes = map[string]string{
	"telemetry:read":        "Read every trace, log and metric the instance holds.",
	"dashboards:manage-own": "Create and edit dashboards you own. Owner-scoped for every role, including admin.",
	"ingest:read-metadata":  "See ingest settings, but not the token itself.",
	"alerts:manage":         "Create, change and delete alert rules.",
	"agent:run":             "Run the chat investigator, which calls a model provider and acts on the instance's behalf.",
	"ingest:manage":         "Rotate the ingest token.",
	"users:manage":          "Create, change and remove user accounts and their roles.",
	"operations:read":       "Read the instance's own internals: Prometheus metrics and, when enabled, the profiling endpoints.",
}

// roleOrder is least to most privileged, which is the order a reader compares
// them in. Derived membership is checked against it so a new role cannot appear
// only at the end of the table by accident.
var roleOrder = []string{"viewer", "operator", "admin"}

func renderRoles() ([]byte, error) {
	roles := api.RoleCapabilities()
	caps := api.AllCapabilities()

	for _, role := range roleOrder {
		if _, ok := roles[role]; !ok {
			return nil, fmt.Errorf(
				"role %q is listed in roleOrder but the middleware does not define it",
				role,
			)
		}
	}
	if len(roles) != len(roleOrder) {
		var unlisted []string
		for role := range roles {
			if !contains(roleOrder, role) {
				unlisted = append(unlisted, role)
			}
		}
		sort.Strings(unlisted)
		return nil, fmt.Errorf(
			"the middleware defines role(s) %s that roleOrder does not place; "+
				"add them to roleOrder in cmd/fanout-docgen/roles.go",
			strings.Join(unlisted, ", "),
		)
	}

	for _, capability := range caps {
		if capabilityNotes[capability] == "" {
			return nil, fmt.Errorf(
				"capability %q has no entry in capabilityNotes in cmd/fanout-docgen/roles.go; "+
					"describe what it permits rather than publishing a bare name",
				capability,
			)
		}
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: \"Roles\"\n")
	b.WriteString("description: \"The three Fanout roles and the capabilities each one carries.\"\n")
	b.WriteString("summary: \"viewer, operator and admin, and exactly what each is permitted to do — taken from the authorization table the server enforces.\"\n")
	b.WriteString("read_when:\n")
	b.WriteString("  - \"You are deciding which role to give someone.\"\n")
	b.WriteString("  - \"You are mapping identity-provider groups onto Fanout roles.\"\n")
	b.WriteString("  - \"A request came back 403 and you want to know which capability it needed.\"\n")
	b.WriteString("status: preview\n")
	b.WriteString("generated: true\n")
	b.WriteString("---\n\n")

	b.WriteString("{/* Generated by cmd/fanout-docgen from internal/api. Edit the generator, not this page. */}\n\n")

	b.WriteString("Fanout has three roles. They are fixed — there is no custom role builder, and\n")
	b.WriteString("a user holds exactly one.\n\n")

	b.WriteString("Every protected route names a capability rather than a role, and a role is a\n")
	b.WriteString("set of capabilities. The table below is that set, read from the same map the\n")
	b.WriteString("middleware consults, so it cannot describe a permission the server does not\n")
	b.WriteString("grant.\n\n")

	b.WriteString("| Capability |")
	for _, role := range roleOrder {
		fmt.Fprintf(&b, " %s |", role)
	}
	b.WriteString("\n|---|")
	for range roleOrder {
		b.WriteString("---|")
	}
	b.WriteString("\n")

	for _, capability := range caps {
		fmt.Fprintf(&b, "| `%s` |", capability)
		for _, role := range roleOrder {
			if contains(roles[role], capability) {
				b.WriteString(" ✓ |")
			} else {
				b.WriteString(" — |")
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## What each capability permits\n\n")
	for _, capability := range caps {
		fmt.Fprintf(&b, "- `%s` — %s\n", capability, capabilityNotes[capability])
	}

	b.WriteString("\n## Who assigns roles\n\n")
	b.WriteString("In `local` auth mode, roles are managed inside Fanout by an admin.\n\n")
	b.WriteString("In `oidc` mode it depends on configuration. If `FANOUT_OIDC_ADMIN_GROUPS` or\n")
	b.WriteString("`FANOUT_OIDC_OPERATOR_GROUPS` is set, the provider owns every linked user's\n")
	b.WriteString("role and reapplies it on each login; otherwise roles stay local.\n")
	b.WriteString("[Authentication modes](/explanation/authentication-modes) covers the details,\n")
	b.WriteString("including why the last active administrator is never demoted.\n\n")

	b.WriteString(":::caution[A role is not a data boundary]\n")
	b.WriteString("Roles gate capabilities, not rows. Every role that can read telemetry can read\n")
	b.WriteString("all of it — namespaces scope queries, not access. An instance is one trust\n")
	b.WriteString("domain.\n")
	b.WriteString(":::\n")

	roleCount = caps
	return []byte(b.String()), nil
}

func contains(haystack []string, needle string) bool {
	for _, item := range haystack {
		if item == needle {
			return true
		}
	}
	return false
}
