package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/labstack/fanout/internal/api"
)

// routeCount is set by collectRoutes so the summary line can report it.
var routeCount []api.RouteDoc

// collectRoutes finds every route registered under apiDir and asks the
// middleware how it classifies each one.
//
// The two halves use deliberately different techniques, and the reason matters.
// The paths can only come from the source, because a route is an `e.GET("...")`
// call and nothing at runtime enumerates them. The authorization requirement
// must NOT come from the source: classifyRoute is a switch of prefix matches and
// method conditions, and a generator that re-implemented that reading would be a
// second authorization model, free to drift from the one that runs. So the path
// is parsed and the policy is asked.
func collectRoutes(apiDir string) ([]api.RouteDoc, error) {
	entries, err := os.ReadDir(apiDir)
	if err != nil {
		return nil, err
	}

	type reg struct{ method, path string }
	var found []reg
	seen := map[reg]bool{}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") ||
			strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, filepath.Join(apiDir, entry.Name()), nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", entry.Name(), err)
		}

		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			switch sel.Sel.Name {
			case "GET", "POST", "PUT", "PATCH", "DELETE":
			default:
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			path, err := strconv.Unquote(lit.Value)
			if err != nil || !strings.HasPrefix(path, "/") {
				return true
			}
			r := reg{method: sel.Sel.Name, path: path}
			if !seen[r] {
				seen[r] = true
				found = append(found, r)
			}
			return true
		})
	}

	if len(found) == 0 {
		return nil, fmt.Errorf(
			"found no route registrations under %s; has the registration style changed?",
			apiDir,
		)
	}

	docs := make([]api.RouteDoc, 0, len(found))
	for _, r := range found {
		doc, ok := api.DescribeRoute(r.method, r.path)
		if !ok {
			// A registered route the middleware does not classify is either
			// unreachable or unprotected by accident. Neither is something to
			// document quietly.
			return nil, fmt.Errorf(
				"route %s %s is registered but the auth middleware does not classify it; "+
					"add a case to classifyRoute or remove the route",
				r.method, r.path,
			)
		}
		docs = append(docs, doc)
	}

	sort.Slice(docs, func(i, j int) bool {
		if docs[i].Path != docs[j].Path {
			return docs[i].Path < docs[j].Path
		}
		return docs[i].Method < docs[j].Method
	})
	routeCount = docs
	return docs, nil
}

// requirement renders what a caller has to present, in a reader's terms rather
// than the middleware's.
func requirement(doc api.RouteDoc) string {
	switch doc.Policy {
	case api.RoutePolicyPublic:
		return "none"
	case api.RoutePolicyAuthenticated:
		return "any signed-in user"
	case api.RoutePolicyProtocol:
		return "protocol handshake"
	case api.RoutePolicyServiceCredential:
		return fmt.Sprintf("`%s`, or a service credential", doc.Capability)
	case api.RoutePolicyCapability:
		return fmt.Sprintf("`%s`", doc.Capability)
	default:
		return doc.Policy
	}
}

func renderRoutes(routes []api.RouteDoc) []byte {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("title: \"HTTP routes\"\n")
	b.WriteString("description: \"Every HTTP route a Fanout instance serves, and the credential each one requires.\"\n")
	b.WriteString("summary: \"The complete HTTP surface with its authorization requirement, taken from the middleware that enforces it.\"\n")
	b.WriteString("read_when:\n")
	b.WriteString("  - \"You are calling the API and need to know what a route requires.\"\n")
	b.WriteString("  - \"A request came back 401 or 403 and you want to know which capability it wanted.\"\n")
	b.WriteString("generated: true\n")
	b.WriteString("---\n\n")

	b.WriteString("{/* Generated by cmd/fanout-docgen from internal/api. Edit the generator, not this page. */}\n\n")

	b.WriteString("Every route below is served on `FANOUT_HTTP_ADDR` (`:7520` by default).\n")
	b.WriteString("Telemetry does not arrive here — OTLP has its own two listeners, described in\n")
	b.WriteString("[send your first telemetry](/start/send-telemetry).\n\n")

	b.WriteString("The **Requires** column is not a description of the rule. It is the answer the\n")
	b.WriteString("authorization middleware gives for that exact method and path, so a route\n")
	b.WriteString("cannot be documented as public while the server treats it otherwise.\n")
	b.WriteString("Capabilities map to roles in [roles](/reference/roles).\n\n")

	b.WriteString("| Method | Path | Requires |\n")
	b.WriteString("|---|---|---|\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", r.Method, r.Path, requirement(r))
	}

	b.WriteString("\n## What the requirements mean\n\n")
	b.WriteString("- **none** — reachable without a credential. The health endpoints are\n")
	b.WriteString("  deliberately here: a probe that needs a credential fails for the wrong\n")
	b.WriteString("  reason during an outage.\n")
	b.WriteString("- **any signed-in user** — a session, but no particular capability.\n")
	b.WriteString("- **protocol handshake** — the OAuth and MCP endpoints, which authenticate\n")
	b.WriteString("  as part of their own protocol rather than through the middleware.\n")
	b.WriteString("- **a named capability** — the caller's role must carry it.\n")
	b.WriteString("- **or a service credential** — additionally reachable without a browser\n")
	b.WriteString("  session, which is how a scraper reaches the metrics endpoint.\n")

	return []byte(b.String())
}
