package mcp

const m2SpecGuide = `state_timeline needs at least one threshold marked warn or bad, rather than only ok. Annotations attach only to timeseries, heatmap and state_timeline panels, scoped by service and namespace filters. drill: logs needs query.from=logs. Drill is not available on metrics. Every table format's field must exist in the returned frame; formatting cannot reference an absent column. A structured-table sparkline field must be a measure alias from that table's query. service_link needs variable to name the query or custom variable selected by the link. highlight applies to logs and log_patterns, at most 200 characters. split: deploy needs a service equality filter, as a literal or a single-value variable; other filters are allowed. When the service is All, a split: deploy panel shows the plain bar with a note explaining the missing service scope. Use service_map for dependency context, health for service health; neither proves causality.`

const investigationExample = `{"name":"Investigation shapes","annotations":{"deploys":true,"anomalies":true},"variables":[{"name":"service","kind":"query","from":"spans","field":"service"}],"panels":[{"id":"latency_heat","title":"Latency over time","viz":"heatmap","query":{"from":"spans","where":["service = $service"],"measures":["count()"],"bucket":"auto","histogram":{"field":"duration_ms","buckets":"log2"}},"drill":"traces"},{"id":"latency_hist","title":"Latency by operation","viz":"histogram","query":{"from":"spans","where":["service = $service"],"measures":["count()"],"by":["operation"],"histogram":{"field":"duration_ms","buckets":"log2"}},"drill":"traces"},{"id":"items","title":"Calls versus tail latency","viz":"scatter","query":{"from":"spans","where":["service = $service"],"measures":["count() as rows","p95(duration_ms) as tail_latency"],"by":["operation"]},"drill":"traces"},{"id":"states","title":"Error states","viz":"state_timeline","query":{"from":"spans","where":["service = $service"],"measures":["error_rate()"],"by":["operation"],"bucket":"auto"},"thresholds":[{"value":5,"status":"bad"}],"drill":"traces"},{"id":"log_rows","title":"Recent logs","viz":"logs","query":{"from":"logs","where":["service = $service"],"sort":"time","limit":100},"drill":"logs"},{"id":"patterns","title":"Repeated log patterns","viz":"log_patterns","query":{"from":"logs","where":["service = $service"],"measures":["count()"],"by":["body_template"],"bucket":"auto","limit":50},"drill":"logs"},{"id":"trace_rows","title":"Slow traces","viz":"traces","query":{"from":"spans","where":["service = $service"],"sort":"duration_ms","limit":20},"drill":"traces"},{"id":"map","title":"Service calls","viz":"service_map","query":{"from":"spans"}},{"id":"health","title":"Service health","viz":"health","query":{"from":"spans"}}]}`

const paymentExample = `{"name":"Interaction shapes","variables":[{"name":"service","kind":"query","from":"spans","field":"service"}],"panels":[{"id":"hist","title":"Metric distribution","viz":"histogram","query":{"from":"metrics","where":["service = $service"],"measures":["count()"],"histogram":{"field":"value","buckets":"explicit"}}},{"id":"table","title":"Service calls and trends","viz":"table","query":{"from":"spans","measures":["count() as calls"],"by":["service"]},"options":{"columns":[{"field":"service","format":"service_link","variable":"service"},{"field":"calls","format":"sparkline"}]}},{"id":"prior","title":"Service calls one day earlier","viz":"bar","query":{"from":"spans","measures":["count()"],"by":["service"]},"click":{"set_variable":"service"},"time":{"shift":"1d"}}]}`

const specGuide = baseSpecGuide + " " + m2SpecGuide + " Example 1: Reference shapes; use only the types the question needs. " + investigationExample + " Example 2: Reference shapes; use only the types the question needs. " + paymentExample
