import type { Message } from '@ag-ui/client';
import server from '../../../scripts/dashboard-eval/testdata/server.json';

// Generated by TestDashboardEvalGoldensCurrent through Runtime.execute.
export function toolError(id:string,key:keyof typeof server.tool_errors,live=false):Message {
 const value=server.tool_errors[key];
 return {id:`r-${id}`,role:'tool',toolCallId:id,content:value.content,...(live?{}:{error:value.error})};
}
